name: payroll_calculator
description: A simple Payroll and Tax Calculator app.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_test:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
include: package:flutter_lints/flutter.yaml

